# Generated by Django 5.2 on 2025-10-16 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='subject',
        ),
    ]
