# Generated by Django 5.2 on 2025-10-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_title_meeting_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='description',
            new_name='agenda',
        ),
    ]
