# Generated by Django 5.2 on 2025-10-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_description_meeting_agenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='starttime',
            new_name='event_time',
        ),
    ]
